# -*- coding: utf-8 -*-
"""Clase5_Challenge4_Student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFCulO4LgoogZSChRIBEtT8tRgUuPSl5

<div style='background:#8B0000; padding:20px; border-radius:8px; margin-bottom:10px'>
<h1 style='color:white; text-align:center; margin:0'>Reconocimiento de Patrones</h1>
<h2 style='color:#ffcccc; text-align:center; margin:5px 0 0 0'>Challenge 4 — Árboles de Decisión, Random Forest y XGBoost</h2>
<p style='color:#ffaaaa; text-align:center; margin:5px 0 0 0'>Ingeniería Biomédica · UPCH · 2026-1</p>
</div>

## Contexto clínico

Retomamos el dataset **Heart Failure Prediction** (Kaggle, fedesoriano, 2021) que ya conoces del Challenge 1.
En ese challenge lo exploraste y preprocesaste; aquí tu misión es **construir, analizar y comparar modelos basados en árboles**.

La pregunta clínica sigue siendo la misma: dado el perfil de un paciente (**Edad, Colesterol, ST_Slope, MaxHR...**), ¿podemos predecir si tiene enfermedad cardíaca?

Los árboles de decisión son especialmente poderosos en datos biomédicos tabulares porque:
- **Son interpretables**: el médico puede trazar exactamente cómo se llegó a un diagnóstico.
- **Capturan no-linealidades** y umbrales clínicos (ej: Oldpeak > 1.5 → riesgo elevado).
- **Random Forest y XGBoost** extienden esta idea con ensambles que reducen el sobreajuste.

---
> **Dataset:** `heart.csv` (ya descargado desde el Challenge 1)  
> **Fuente:** fedesoriano. (2021). *Heart Failure Prediction Dataset*. Kaggle. https://www.kaggle.com/fedesoriano/heart-failure-prediction  
> **Variables:** Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope → **HeartDisease** (0/1)

### Estructura de carpetas
```
Clase5_Challenge4/
├── Challenge4_ApellidoNombre.ipynb
└── heart.csv     ← el mismo del Challenge 1
```
"""



"""---
---
## Ejercicio 1 — Diseño previo al código

### 1.1 — Diagnóstico esperado

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

Antes de escribir una línea de código, responde las siguientes preguntas:

**1. ¿Un árbol de decisión profundo tiene más sesgo o más varianza que un árbol *prepodado* (profundidad controlada)? Relaciona con la descomposición sesgo-varianza:**

$$\text{Error esperado}(x) = \underbrace{\left(y^\star - \mathbb{E}[y]\right)^2}_{\text{sesgo}^2} + \underbrace{\text{Var}(y)}_{\text{varianza}} + \underbrace{\text{Var}(t)}_{\text{error de Bayes}}$$

**📝 Tu respuesta (edita esta celda):**  
Árbol profundo   → sesgo bajo / varianza alta  
Árbol prepodado → sesgo alto / varianza baja  
Justificación: Un árbol profundo tiene la capacidad de ajustarse perfectamente a los datos, lo que reduce el sesgo, pero esto lo hace más susceptible a sobreajustarse a los detalles de los datos de entrenamiento, aumentando así la varianza.
Un árbol prepodado, al limitar la profundidad, reduce la complejidad del modelo, aumentando el sesgo, pero a su vez disminuye la varianza al evitar el sobreajuste.

---

**2. ¿Qué diferencia hay entre Gini e Entropía como criterios de división? ¿Cuándo llevan a árboles distintos?**

| Criterio | Fórmula | Rango (2 clases) |
|---|---|---|
| Gini | Gini=1−∑(pi2​) | [0,0.5]
| Entropía | −∑(pi​log(pi​)) | [0,log(c)]|

**📝 Tu respuesta:**Gini y Entropía son dos formas de medir la impureza de un nodo en un árbol de decisión, pero calculan la dispersión de manera diferente.
El criterio Gini tiende a ser más rápido en la práctica, mientras que Entropía tiene una mayor capacidad para dividir los datos, pero no siempre lleva a mejores resultados.
Aunque ambos se utilizan para dividir los nodos, en ciertos casos, como con clases muy desbalanceadas, Entropía puede generar árboles diferentes a los de Gini.
---

**3. ¿Por qué Random Forest reduce la varianza pero NO el sesgo?**

Pista: $\bar{y} = \frac{1}{M}\sum_{m=1}^M y_m$ — ¿qué pasa con $\mathbb{E}[\bar{y}]$ y con $\text{Var}(\bar{y})$?

**📝 Tu respuesta:** ___

---

**4. Completa la tabla comparando bagging (RF) y boosting (XGBoost):**

| | Bagging / RF | Boosting / XGBoost |
|---|---|---|
| Entrenamiento | Bagging / RF | Boosting / XGBoost |
| Objetivo (sesgo/varianza) | Reducir varianza | Reducir sesgo |
| Riesgo principal | Alta varianza (sobreajuste) | Alta complejidad (sobreajuste por corrección excesiva)|

---

**5. ¿Qué features del dataset heart.csv (que ya conoces del Challenge 1) esperas que sean las más importantes para predecir HeartDisease? Justifica clínicamente.**

**📝 Tu respuesta:**Árbol de decisión prepodado es ideal cuando se busca explicabilidad en el modelo y no se quiere sobreajuste.
Random Forest es mejor cuando se busca mejorar el rendimiento general sin sacrificar demasiada interpretabilidad.
XGBoost es recomendado cuando se necesita precisión máxima en el desempeño, pero puede ser más difícil de interpretar debido a su complejidad.

### 1.2 — Matemática de la impureza

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

Usando las fórmulas de **Gini** e **Entropía**:

$$G(n) = 1 - \sum_k p_k^2 \qquad H(n) = -\sum_k p_k \log_2 p_k$$

**Calcula para un nodo con 20 pacientes: 10 con enf. (pos), 10 sin enf. (neg):**

$$G(n) = 1 - \sum_k p_k^2 \quad \text{y} \quad H(n) = - \sum_k p_k \log_2 p_k$$

$$ H(\text{raíz}) = - \left( \frac{10}{20} \right) \log_2\left( \frac{10}{20} \right) - \left( \frac{10}{20} \right) \log_2\left( \frac{10}{20} \right) = 1 \text{ bit}$$

---

**Después de dividir por "ST\_Slope\_Up = 1":**

| Rama | Muestras | $p_+$ | Gini | Entropía |
|---|---|---|---|---|
| Izq (ST_Slope_Up=1) | 10 | 5 | 0.48| 0.97 |
| Der (ST_Slope_Up=0) | 10 | 5 | 0.48| 0.97 |

**Reducción de impureza / ganancia de información:**

ΔGini = G(raíz) - ( (10/20) × G(Izq) + (10/20) × G(Der) ) = 0.02

IGH = H(raíz) - ( (10/20) × H(Izq) + (10/20) × H(Der) ) = 0.03 bits

**📝 Completa los blancos arriba.**

### 1.3 — Pipeline completo

Completa el diagrama de pipeline para este challenge:

```
heart.csv
    │
    ▼
[ Paso A ] Cargar datos (heart.csv)
    │
    ▼
[ Paso B ] Train/Test split estratificado (80/20)
     → Aquí se divide. ¿Por qué es importante este orden?
     → **Es importante este orden porque se garantiza que los datos de entrenamiento y prueba estén balanceados en cuanto a las clases.**
    │
    ├─── TRAIN (80%) ──────────────────────────────────────┐
    │                                                     │
    ▼                                                     │
[ Paso C ] Preprocesamiento (limpieza, imputación, normalización, etc.)                                           │
    │                                                     │
    ▼                                                     │
[ Paso D ]  Modelos: Árbol de decisión, Random Forest, XGBoost │
    │                                                     │
    └─── TEST (20%) ── ___ ──────────────────────────── ──┘
    │
    ▼
[ Paso G ] Implementación final
```

**📝 Tu respuesta (edita esta celda):** completa los blancos del diagrama.

---
## Ejercicio 2 — Setup y carga de datos

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import pandas as pd

DATA_PATH = Path('/content/drive/MyDrive/2026/Patrones/SEMANA5') / 'heart.csv'

print("Ruta:", DATA_PATH)
print("¿Existe?:", DATA_PATH.exists())

df = pd.read_csv(DATA_PATH)
df.head()

"""### Paso 2.1 — Librerías"""

# ===============================
# PASO 2.1 — LIBRERÍAS
# ===============================

UPCH_RED    = "#8B0000"
UPCH_BLUE   = "#1565C0"
UPCH_GREEN  = "#2E7D32"
UPCH_ORANGE = "#E65100"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# ✅ Decision Tree
from sklearn.tree import DecisionTreeClassifier, plot_tree

# ✅ Random Forest
from sklearn.ensemble import RandomForestClassifier

# Otros
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import (train_test_split, cross_val_score, StratifiedKFold)

from sklearn.metrics import (
    accuracy_score, recall_score, precision_score,
    f1_score, confusion_matrix, ConfusionMatrixDisplay,
    roc_curve, auc, classification_report
)

# ===============================
# XGBOOST
# ===============================
try:
    from xgboost import XGBClassifier
    print("XGBoost disponible ✓")
except ImportError:
    import subprocess
    subprocess.run(['pip', 'install', 'xgboost', '-q'])
    from xgboost import XGBClassifier
    print("XGBoost instalado ✓")

# ===============================
# CONFIGURACIÓN
# ===============================

plt.rcParams['figure.dpi'] = 120

# 🔥 AJUSTA ESTA RUTA A TU DRIVE
BASE = Path('/content/drive/MyDrive/2026/Patrones/SEMANA5')

print("Setup completo ✓")

"""### Paso 2.2 — Carga del dataset"""

# ── Carga del dataset ──────────────────────────────────────────

df_raw = pd.read_csv(BASE / 'heart.csv')
print(f'Shape: {df_raw.shape}')
print(f'Columnas: {list(df_raw.columns)}')
df_raw.head()

"""### Paso 2.3 — Preprocesamiento compacto"""

# ── Preprocesamiento compacto (recapitulando Challenge 1) ──────
df = df_raw.copy()

# 1. Cholesterol = 0 → NaN
df.loc[df['Cholesterol'] == 0, 'Cholesterol'] = np.nan

# 2. One-Hot Encoding
cat_cols = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

# 3. Separar features y target
X_raw         = df.drop(columns='HeartDisease').values.astype(np.float64)
y             = df['HeartDisease'].values.astype(int)
feature_names = df.drop(columns='HeartDisease').columns.tolist()

# 4. Train/Test split estratificado
X_train, X_test, y_train, y_test = train_test_split(
    X_raw, y, test_size=0.2, random_state=42, stratify=y
)

# ===============================
# ✅ IMPUTACIÓN
# ===============================
imputer = SimpleImputer(strategy='median')

X_train = imputer.fit_transform(X_train)   # ✔ fit + transform
X_test  = imputer.transform(X_test)        # ✔ solo transform

# ===============================
# ✅ ESCALADO
# ===============================
scaler = StandardScaler()

X_train_sc = scaler.fit_transform(X_train)   # ✔ fit + transform
X_test_sc  = scaler.transform(X_test)        # ✔ solo transform

# ===============================
# CHECK
# ===============================
print(f'Train: {X_train.shape}  (0: {(y_train==0).sum()}, 1: {(y_train==1).sum()})')
print(f'Test:  {X_test.shape}   (0: {(y_test==0).sum()},  1: {(y_test==1).sum()})')
print(f'Features ({len(feature_names)}): {feature_names[:5]} ...')

"""---
# PARTE 1 — Árbol de Decisión
## Ejercicio 3 — Árbol base y curva de profundidad

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

### Paso 3.1 — Árbol base (max_depth=3) y visualización
"""

# ── Árbol de decisión base (max_depth=3) ─────────────────────────

# ⚠️ Usamos X_train / X_test (sin escalar)

# TODO 5: crear el modelo
dt_base = DecisionTreeClassifier(
    max_depth=3,
    criterion='gini',
    min_samples_leaf=5,
    random_state=42
)

# TODO 6: entrenar
dt_base.fit(X_train, y_train)

# Predicción
y_pred_base = dt_base.predict(X_test)

# Métrica
acc_base = accuracy_score(y_test, y_pred_base)

print(f'Accuracy DT (max_depth=3): {acc_base:.4f}')
print(f'Nodos totales: {dt_base.tree_.node_count} | Hojas: {dt_base.get_n_leaves()}')

# ===============================
# TODO 7: VISUALIZACIÓN
# ===============================
fig, ax = plt.subplots(figsize=(22, 8))

plot_tree(
    dt_base,
    feature_names=feature_names,
    class_names=['Sin enf.', 'Con enf.'],
    filled=True,
    rounded=True,
    fontsize=8
)

ax.set_title(
    'Árbol de Decisión (max_depth=3) — Heart Disease',
    fontsize=14,
    fontweight="bold",
    color=UPCH_RED
)

plt.tight_layout()
plt.savefig('dt_visualizacion.png', dpi=150, bbox_inches='tight')
plt.show()

print('¿Qué feature aparece en la raíz del árbol? ¿Tiene sentido clínicamente?')

"""### Paso 3.2 — Curva de profundidad"""

# ── Curva de profundidad: train vs test accuracy ─────────────────

depths   = list(range(1, 21))
acc_train = []
acc_test  = []
acc_cv    = []

cv_depth = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for d in depths:

    # TODO 8: crear modelo
    dt = DecisionTreeClassifier(
        max_depth=d,
        criterion='gini',
        min_samples_leaf=5,
        random_state=42
    )

    dt.fit(X_train, y_train)

    # ===============================
    # TODO 9: accuracy train y test
    # ===============================
    acc_train.append(accuracy_score(y_train, dt.predict(X_train)))
    acc_test.append(accuracy_score(y_test, dt.predict(X_test)))

    # ===============================
    # TODO 10: cross-validation (SOLO TRAIN)
    # ===============================
    scores = cross_val_score(
        dt,
        X_train,
        y_train,
        cv=cv_depth,
        scoring='accuracy'
    )

    sc_cv = scores.mean()
    acc_cv.append(sc_cv)

# ===============================
# SELECCIÓN DEL MEJOR MODELO
# ===============================
best_idx   = np.argmax(acc_cv)
best_depth = depths[best_idx]

print(f'Mejor max_depth (CV-5 en train): depth={best_depth} → acc_cv={acc_cv[best_idx]:.4f}')

# ===============================
# GRÁFICO
# ===============================
fig, ax = plt.subplots(figsize=(11, 5))

ax.plot(depths, acc_train, 'o-', color=UPCH_BLUE,  lw=2, label='Train')
ax.plot(depths, acc_test,  's-', color=UPCH_RED,   lw=2, label='Test')
ax.plot(depths, acc_cv,    '^-', color=UPCH_GREEN, lw=2, label='CV-5 (train)')

ax.axvline(best_depth, color=UPCH_GREEN, ls='--', lw=2.5, label=f'best_depth={best_depth}')

ax.set_xlabel('max_depth', fontsize=12)
ax.set_ylabel('Accuracy', fontsize=12)

ax.set_title(
    'Efecto de max_depth — Árbol de Decisión - Heart Disease',
    fontsize=13,
    fontweight='bold',
    color=UPCH_RED
)

ax.legend(fontsize=10)
ax.grid(True, alpha=0.3)

ax.set_ylim(0.6, 1.05)

plt.tight_layout()
plt.savefig('dt_curva_profundidad.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 3.2 — Interpretación

**📝 Tu respuesta (edita esta celda):**

**1. ¿Por qué la accuracy de train sube mientras la de test cae al aumentar max_depth?**  
A medida que aumenta la profundidad del árbol, el modelo se vuelve más complejo y logra ajustarse mejor a los datos de entrenamiento, capturando incluso patrones muy específicos o ruido, lo que incrementa el accuracy en train.
Sin embargo, esta mayor complejidad reduce su capacidad de generalización, por lo que el desempeño en datos no vistos (test) disminuye, evidenciando sobreajuste.

**2. ¿En qué profundidad empieza el sobreajuste? ¿Cómo lo identificas en la gráfica?**  
El sobreajuste comienza aproximadamente a partir de max_depth ≈ 4 o 5.
Se identifica porque:

El accuracy de train sigue aumentando
Mientras que el accuracy de test deja de mejorar e incluso disminuye
Además, la curva de validación cruzada (CV) también empieza a bajar

Esto indica que el modelo está aprendiendo detalles específicos del entrenamiento que no generalizan bien.

**3. ¿Qué analogía clínica tiene el sobreajuste de un árbol muy profundo?**  
El sobreajuste puede compararse con un médico que memoriza casos clínicos específicos en lugar de comprender patrones generales de la enfermedad.
Esto puede llevar a diagnósticos muy precisos en pacientes ya conocidos, pero errores al enfrentarse a nuevos pacientes, ya que el razonamiento no es generalizable.

### Paso 3.3 — Feature Importance

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>
"""

# ── Árbol óptimo + Feature Importance ───────────────────────────

# TODO 11: crea y entrena el árbol con best_depth
dt_opt = DecisionTreeClassifier(
    max_depth=best_depth,
    criterion='gini',
    min_samples_leaf=5,
    random_state=42
)

dt_opt.fit(X_train, y_train)  # ← FALTABA ESTO

# Importancias
importances_dt = dt_opt.feature_importances_

# TODO 12: ordenar de mayor a menor
idx_sorted = np.argsort(importances_dt)

# ===============================
# GRÁFICO
# ===============================
fig, ax = plt.subplots(figsize=(10, 6))

ax.barh(
    [feature_names[i] for i in idx_sorted[::-1]],
    importances_dt[idx_sorted[::-1]],
    color=[UPCH_RED if i == 0 else UPCH_BLUE
           for i in range(len(feature_names))][::-1],
    alpha=0.85
)

ax.set_xlabel('Importancia (reducción media de Gini)', fontsize=11)
ax.set_title(
    f'Feature Importance — Árbol de Decisión regularizado (depth={best_depth})',
    fontsize=12,
    fontweight='bold',
    color=UPCH_RED
)

ax.grid(True, axis='x', alpha=0.3)

plt.tight_layout()
plt.savefig('dt_feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()

# ===============================
# TOP FEATURES
# ===============================
print('Top 5 features más importantes:')
for r, i in enumerate(idx_sorted[::-1][:5]):
    print(f'{r+1}. {feature_names[i]:<40} {importances_dt[i]:.4f}')

print()
print('→ ¿Coincide con tus predicciones clínicas del Ejercicio 1.1?')

"""### Paso 3.4 — Métricas y matriz de confusión"""

# ── Métricas finales Árbol de Decisión ─────────────────────────

y_pred_dt = dt_opt.predict(X_test)

# TODO 13: calcular métricas
acc_dt = accuracy_score(y_test, y_pred_dt)
rec_dt = recall_score(y_test, y_pred_dt)
prec_dt = precision_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)

print('=' * 52)
print(f' Árbol de Decisión regularizado (max_depth={best_depth})')
print('=' * 52)
print(f' Accuracy : {acc_dt:.4f}')
print(f' Recall   : {rec_dt:.4f}')
print(f' Precision: {prec_dt:.4f}')
print(f' F1-Score : {f1_dt:.4f}')
print()

print(classification_report(
    y_test,
    y_pred_dt,
    target_names=['Sin enf.', 'Con enf.']
))

# ===============================
# MATRIZ DE CONFUSIÓN
# ===============================
fig, ax = plt.subplots(figsize=(5.5, 4.5))

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred_dt,
    display_labels=['Sin enf.', 'Con enf.'],
    cmap='Blues',
    ax=ax
)

ax.set_title(
    f'Árbol de Decisión regularizado (depth={best_depth})\nAccuracy = {acc_dt:.4f}',
    fontsize=11,
    fontweight='bold',
    color=UPCH_RED
)

plt.tight_layout()
plt.savefig('cm_dt.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
# PARTE 2 — Random Forest
## Ejercicio 4 — Efecto de n_estimators y optimización

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>

### Paso 4.1 — Efecto de n_estimators
"""

# ── Efecto de n_estimators en Random Forest ─────────────────────

n_list = [1, 5, 10, 20, 50, 100, 200, 300]
acc_rf_train = []
acc_rf_test  = []
acc_rf_oob   = []

for n in n_list:

    # TODO 15: crear modelo
    rf = RandomForestClassifier(
        n_estimators=n,
        max_features='sqrt',
        oob_score=(n >= 2),   # solo válido si n >= 2
        random_state=42,
        n_jobs=-1
    )

    rf.fit(X_train, y_train)

    # Accuracy train/test
    acc_rf_train.append(accuracy_score(y_train, rf.predict(X_train)))
    acc_rf_test.append(accuracy_score(y_test, rf.predict(X_test)))

    # TODO 16: OOB score
    if n >= 2:
        acc_rf_oob.append(rf.oob_score_)
        oob_str = f'{rf.oob_score_:.4f}'
    else:
        acc_rf_oob.append(np.nan)
        oob_str = 'N/A'

    print(f'n={n:>3}  train={acc_rf_train[-1]:.4f}  test={acc_rf_test[-1]:.4f}  OOB={oob_str}')

# ===============================
# GRÁFICO
# ===============================
fig, ax = plt.subplots(figsize=(11, 5))

ax.plot(n_list, acc_rf_train, 'o-', color=UPCH_BLUE,  lw=2, label='Train')
ax.plot(n_list, acc_rf_test,  's-', color=UPCH_RED,   lw=2, label='Test')
ax.plot(n_list, acc_rf_oob,   '^-', color=UPCH_GREEN, lw=2, label='OOB')

ax.set_xlabel('n_estimators', fontsize=12)
ax.set_ylabel('Accuracy', fontsize=12)

ax.set_title(
    'Random Forest — Efecto de n_estimators - Heart Disease',
    fontsize=13,
    fontweight='bold',
    color=UPCH_RED
)

ax.legend(fontsize=10)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('rf_n_estimators.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 4.1 — Interpretación

**📝 Tu respuesta (edita esta celda):**

**1. ¿Por qué la accuracy de RF converge al aumentar n_estimators?**  
Pista: $\text{Var}(\bar{y}) = \left(\frac{1-\rho}{M} + \rho\right)\sigma^2$  
A medida que aumenta el número de árboles en Random Forest, el modelo reduce la varianza al promediar múltiples árboles independientes.
Esto hace que el desempeño se vuelva más estable y la accuracy tienda a converger.
Según la teoría, la varianza disminuye aproximadamente como:
Var(ŷ) = (1/M + ρ)σ², donde M es el número de árboles y ρ la correlación entre ellos.
Por ello, al aumentar M, la mejora se vuelve cada vez menor hasta estabilizarse.

**2. ¿Qué es el OOB score? ¿Por qué es útil?**  
El OOB (Out-Of-Bag) score es una estimación del desempeño del modelo utilizando muestras que no fueron seleccionadas durante el entrenamiento de cada árbol (bootstrap).
Es útil porque permite evaluar el modelo sin necesidad de un conjunto de validación adicional, proporcionando una medida interna del rendimiento.

**3. ¿RF tiene más o menos sesgo que un árbol individual del mismo max_depth?**  
Random Forest tiene generalmente mayor sesgo pero menor varianza en comparación con un árbol individual.
Esto se debe a que promedia múltiples árboles, reduciendo el sobreajuste y mejorando la capacidad de generalización.

### Paso 4.2 — Barrido max_features × max_depth
"""

# ── Random Forest optimizado (barrido max_features x max_depth) ─

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

mf_list = ['sqrt', 'log2', None]
md_list = [None, 5, 10, 15]

print('Barrido max_features × max_depth (CV-5):')
print(f'{"max_features":<15} {"max_depth":<12} {"CV acc"}')
print('-' * 42)

best_score_rf = 0
best_mf, best_md = None, None

for mf in mf_list:
    for md in md_list:

        # ✅ CREAR MODELO
        rf_cv = RandomForestClassifier(
            n_estimators=100,
            max_features=mf,
            max_depth=md,
            random_state=42,
            n_jobs=-1
        )

        # ✅ CROSS VALIDATION
        scores = cross_val_score(
            rf_cv,
            X_train,
            y_train,
            cv=cv,
            scoring='accuracy'
        )

        sc = scores.mean()

        mf_s = str(mf) if mf else 'all'
        md_s = str(md) if md else 'None'

        print(f'{mf_s:<15} {md_s:<12} {sc:.4f}')

        if sc > best_score_rf:
            best_score_rf = sc
            best_mf, best_md = mf, md

print()
print(f'\nMejores parámetros: max_features={best_mf}, max_depth={best_md}')
print(f'CV accuracy: {best_score_rf:.4f}')

"""### Paso 4.3 — Random Forest final"""

# ── Random Forest final ─────────────────────────────────────────

rf_final = RandomForestClassifier(
    n_estimators=200,
    max_features=best_mf,
    max_depth=best_md,
    oob_score=True,
    random_state=42,
    n_jobs=-1
)

rf_final.fit(X_train, y_train)

y_pred_rf = rf_final.predict(X_test)

# TODO 20: métricas
acc_rf = accuracy_score(y_test, y_pred_rf)
rec_rf = recall_score(y_test, y_pred_rf)
prec_rf = precision_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

print('=' * 52)
print(f' Random Forest (n=200, mf={best_mf}, depth={best_md})')
print('=' * 52)
print(f' OOB Score: {rf_final.oob_score_:.4f}')
print(f' Accuracy : {acc_rf:.4f}')
print(f' Recall   : {rec_rf:.4f}')
print(f' Precision: {prec_rf:.4f}')
print(f' F1-Score : {f1_rf:.4f}')
print()
print(f'↑ Δ Accuracy vs DT: {acc_rf - acc_dt:+.4f}')

"""### Paso 4.4 — Feature Importance: DT vs RF"""

# ── Feature Importance: DT vs RF ───────────────────────────────

# TODO 21
importances_rf = rf_final.feature_importances_

fig, axes = plt.subplots(1, 2, figsize=(17, 6))

for ax, imp, title, color in zip(
    axes,
    [importances_dt, importances_rf],
    [f'Árbol de Decisión regularizado (depth={best_depth})',
     'Random Forest (200 árboles)'],
    [UPCH_BLUE, UPCH_RED]
):
    idx = np.argsort(imp)
    ax.barh([feature_names[i] for i in idx], imp[idx], color=color, alpha=0.8)
    ax.set_xlabel('Importancia', fontsize=10)
    ax.set_title(title, fontsize=11, fontweight='bold')
    ax.grid(True, axis='x', alpha=0.3)

plt.suptitle('Feature Importance — DT vs Random Forest - Heart Disease',
             fontsize=12, fontweight='bold', color=UPCH_RED)

plt.tight_layout()
plt.savefig('fi_dt_vs_rf.png', dpi=150, bbox_inches='tight')
plt.show()

# Correlación
print('Correlación entre importancias DT y RF:')
print(f'{np.corrcoef(importances_dt, importances_rf)[0,1]:.4f}')

print('\n→ ¿Las RF importancias son más o menos estables que las del DT individual?')

"""---
# PARTE 3 — XGBoost
## Ejercicio 5 — Gradient Boosting

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>

### Paso 5.1 — XGBoost base
"""

# ── XGBoost base ───────────────────────────────────────────────

xgb_base = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss',
    verbosity=0
)

# Entrenar
xgb_base.fit(X_train, y_train)

# Predicción
y_pred_xgb_base = xgb_base.predict(X_test)

# Accuracy
acc_xgb_base = accuracy_score(y_test, y_pred_xgb_base)

print(f'Accuracy XGBoost base (lr=0.1, depth=4, n=100): {acc_xgb_base:.4f}')
print()
print('¿XGBoost base supera al Árbol de Decisión y al Random Forest?')

"""### Paso 5.2 — Tuning: learning_rate × n_estimators"""

# ── Tuning: barrido learning_rate × n_estimators ───────────────

lr_list = [0.01, 0.05, 0.1, 0.2, 0.3]
n_est_list = [50, 100, 200, 300]

print('Barrido learning rate × n_estimators (CV-5):')
print(f'{"lr":<8} {"n_est":<8} {"CV acc"}')
print('-' * 28)

best_score_xgb = 0
best_lr, best_n_xgb = 0.1, 100

for lr in lr_list:
    for n_est in n_est_list:

        # TODO 24: crear modelo
        xgb_cv = XGBClassifier(
            learning_rate=lr,
            n_estimators=n_est,
            max_depth=4,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            eval_metric='logloss',
            verbosity=0
        )

        # TODO 25: cross validation
        scores = cross_val_score(
            xgb_cv,
            X_train,
            y_train,
            cv=5,
            scoring='accuracy'
        )

        sc = scores.mean()

        print(f'{lr:<8} {n_est:<8} {sc:.4f}')

        if sc > best_score_xgb:
            best_score_xgb = sc
            best_lr, best_n_xgb = lr, n_est

print()
print(f'\nMejores parámetros: lr={best_lr}, n_estimators={best_n_xgb}')
print(f'CV accuracy: {best_score_xgb:.4f}')

"""### Paso 5.3 — XGBoost final"""

# ── XGBoost final ───────────────────────────────────────────────

# TODO 26: crea el XGBClassifier final con los mejores parámetros
xgb_final = XGBClassifier(
    learning_rate=best_lr,
    n_estimators=best_n_xgb,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss',
    verbosity=0
)

xgb_final.fit(X_train, y_train)

y_pred_xgb = xgb_final.predict(X_test)

# TODO 27: calcula las 4 métricas para XGBoost
acc_xgb  = accuracy_score(y_test, y_pred_xgb)
rec_xgb  = recall_score(y_test, y_pred_xgb)
prec_xgb = precision_score(y_test, y_pred_xgb)
f1_xgb   = f1_score(y_test, y_pred_xgb)

print('=' * 55)
print(f' XGBoost (lr={best_lr}, n={best_n_xgb}, depth=4)')
print('=' * 55)
print(f' Accuracy : {acc_xgb:.4f}')
print(f' Recall   : {rec_xgb:.4f}')
print(f' Precision: {prec_xgb:.4f}')
print(f' F1-Score : {f1_xgb:.4f}')
print()
print(f'↑ Δ Accuracy vs DT: {acc_xgb - acc_dt:+.4f}')
print(f'↑ Δ Accuracy vs RF: {acc_xgb - acc_rf:+.4f}')

"""### Paso 5.4 — Feature Importance comparativa"""

# ── Feature Importance: DT vs RF vs XGBoost ─────────────────────

# TODO 28: extrae las feature importances de xgb_final
importances_xgb = xgb_final.feature_importances_

fig, axes = plt.subplots(1, 3, figsize=(21, 6))

for ax, imp, title, color in zip(
    axes,
    [importances_dt, importances_rf, importances_xgb],
    [
        f'Árbol de Decisión regularizado\n(depth={best_depth})',
        'Random Forest\n(200 árboles)',
        f'XGBoost\n(lr={best_lr}, n={best_n_xgb})'
    ],
    [UPCH_BLUE, UPCH_RED, UPCH_GREEN]
):
    idx = np.argsort(imp)
    ax.barh([feature_names[i] for i in idx], imp[idx], color=color, alpha=0.8)
    ax.set_title(title, fontsize=11, fontweight='bold')
    ax.set_xlabel('Importancia', fontsize=9)
    ax.grid(True, axis='x', alpha=0.3)

plt.suptitle(
    'Feature Importance Comparativa — DT · RF · XGBoost · Heart Disease',
    fontsize=13,
    fontweight='bold',
    color=UPCH_RED
)

plt.tight_layout()
plt.savefig('fi_comparativa.png', dpi=150, bbox_inches='tight')
plt.show()

print('→ ¿Las tres metodologías coinciden en las features más importantes?')

"""---
# PARTE 4 — Comparación Final
## Ejercicio 6 — ROC curves y tabla de métricas

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>

### Paso 6.1 — Curvas ROC
"""

# ── Curvas ROC: DT, RF, XGBoost ───────────────────────────────

fig, ax = plt.subplots(figsize=(8, 7))

for modelo, nombre, color in [
    (dt_opt,  f'Árbol de Decisión regularizado (depth={best_depth})', UPCH_BLUE),
    (rf_final, 'Random Forest (200 árboles)', UPCH_RED),
    (xgb_final, f'XGBoost (lr={best_lr})', UPCH_GREEN)
]:

    # TODO 29: probabilidades clase positiva
    y_score = modelo.predict_proba(X_test)[:, 1]

    # TODO 30: ROC
    fpr, tpr, _ = roc_curve(y_test, y_score)
    roc_auc = auc(fpr, tpr)

    ax.plot(fpr, tpr, lw=2.5, color=color, label=f'{nombre} (AUC = {roc_auc:.3f})')

# Línea base (azar)
ax.plot([0,1], [0,1], 'k--', lw=1.5, label='Clasificador aleatorio')

ax.set_xlabel('Tasa de Falsos Positivos (1 - Especificidad)', fontsize=11)
ax.set_ylabel('Tasa de Verdaderos Positivos (Sensibilidad)', fontsize=11)

ax.set_title(
    'Curvas ROC — Heart Disease · DT · RF · XGBoost',
    fontsize=13,
    fontweight='bold',
    color=UPCH_RED
)

ax.legend(fontsize=10, loc='lower right')
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('roc_comparativa.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 6.2 — Tabla de métricas comparativa"""

# ── Tabla de métricas comparativa ─────────────────────────────

print('=' * 75)
print(' RESUMEN FINAL — Challenge 4: Árboles, RF y XGBoost')
print('=' * 75)
print(f'{"Modelo":<30} {"Accuracy":<12} {"Recall":<12} {"Precision":<12} {"F1":<12}')
print('-' * 75)

# TODO 31
resultados = [
    (f'Árbol de Decisión (d={best_depth})', acc_dt, rec_dt, prec_dt, f1_dt),
    ('Random Forest (n=200)', acc_rf, rec_rf, prec_rf, f1_rf),
    (f'XGBoost (lr={best_lr})', acc_xgb, rec_xgb, prec_xgb, f1_xgb),
]

for nombre, acc, rec, prec, f1 in resultados:
    print(f'{nombre:<30} {acc:.4f}       {rec:.4f}       {prec:.4f}       {f1:.4f}')

"""### Paso 6.3 — Interpretación sesgo-varianza

**📝 Tu respuesta (edita esta celda):**

Completa la tabla:

| Modelo | Sesgo | Varianza | Mecanismo de reducción |
|---|---|---|---|
| Árbol profundo | Bajo | Alto | Ninguno (sobreajuste) |
| Árbol prepodado / profundidad controlada | Medio | media | Regularización (limitando profundidad, min_samples) |
| Random Forest | Media | Baja | Promedio de múltiples árboles (bagging) |
| XGBoost | Bajo | Media-Baja | Boosting secuencial + regularización |

**¿En qué escenario clínico usarías cada modelo? Justifica:**

- **Árbol de Decisión prepodado:** Se utilizaría cuando se requiere alta interpretabilidad, por ejemplo, para explicar decisiones médicas a pacientes o personal clínico. Permite visualizar reglas claras y comprensibles.
- **Random Forest:** Se usaría en escenarios donde se busca un buen equilibrio entre rendimiento y estabilidad, como sistemas de apoyo clínico donde la precisión es importante pero también se requiere robustez frente a datos variables.
- **XGBoost:** Es ideal para sistemas de predicción clínica de alta precisión, como detección temprana de enfermedades, donde maximizar el rendimiento es prioritario. Sin embargo, su menor interpretabilidad lo hace más adecuado como herramienta de apoyo que como modelo explicativo.

---
<div style='background:#f5f5f5; padding:15px; border-left:5px solid #8B0000; border-radius:4px'>
<b>Entrega:</b> Sube tu notebook ejecutado (.ipynb con outputs) a tu carpeta de GitHub del curso.<br>
<b>Nombre del archivo:</b> <code>Challenge4_ApellidoNombreDeAmbos.ipynb</code><br>
<b>Fecha límite:</b> antes de Clase 6
</div>
"""