# -*- coding: utf-8 -*-
"""Clase6_Challenge5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LFuyewqviEGlG2vp5EdXnzCPO9JUqCNz

<div style='background:#8B0000; padding:20px; border-radius:8px; margin-bottom:10px'>
<h1 style='color:white; text-align:center; margin:0'>Reconocimiento de Patrones</h1>
<h2 style='color:#ffcccc; text-align:center; margin:5px 0 0 0'>Challenge 5 — Maldición de la Dimensionalidad, PCA, K-means y DBSCAN</h2>
<p style='color:#ffaaaa; text-align:center; margin:5px 0 0 0'>Ingeniería Biomédica · UPCH · 2026-1</p>
</div>

## Contexto clínico

Pasamos del aprendizaje supervisado al **aprendizaje no supervisado**. En los challenges anteriores conocías la etiqueta de cada paciente; aquí trabajarás **sin etiquetas**.

El dataset es el **Breast Cancer Wisconsin** (UCI / sklearn, 1995): 569 registros de biopsias de mama con 30 features numéricas calculadas a partir de imágenes digitalizadas de aspirado con aguja fina (FNA). Cada feature describe propiedades geométricas y texturales del núcleo celular (radio, textura, perímetro, área, suavidad, compacidad…).

**Pregunta clínica:** ¿Puede un algoritmo no supervisado encontrar subgrupos de tumores que se correspondan con el diagnóstico real (maligno / benigno) sin usar las etiquetas en ningún momento del entrenamiento? Al final del challenge revelaremos las etiquetas para evaluar qué tan bien los clusters recuperan la estructura clínica.

---
> **Fuente:** Wolberg, W. H. et al. (1995). *Breast Cancer Wisconsin (Diagnostic) Dataset*. UCI ML Repository.  
> Disponible directamente en `sklearn.datasets.load_breast_cancer()` — no requiere descarga.

### Estructura de carpetas
```
Clase6_Challenge5/
└── Challenge5_ApellidoNombre.ipynb    ← no se necesita CSV externo
```

---
## Ejercicio 1 — Diseño previo al código

### 1.1 — Maldición de la dimensionalidad

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

**1.** En un hipercubo d-dimensional $[0,1]^d$ con datos uniformes, para capturar una fracción $f$ de los datos con un hipercubo de vecindad de lado $l$, demuestra que:

$$l(f, d) = f^{1/d}$$

Calcula $l(0.01, d)$ para $d = 1, 5, 10, 30$ y completa la tabla:

| $d$ | $l(0.01,\, d)$ | Interpretación |
|---|---|---|
| 1 | f | No cambia, mayor influencia de la dimensión |
| 5 | f^{1/5}$$ | Reducción significativa de la influencia de la dimensión |
| 10 | f^{1/10}$$| Reducción aún más marcada |
| 30 | f^{1/30}$$| La influencia de la dimensión es muy pequeña |

**📝 Tu respuesta:** kNN: En algoritmos como kNN, cuando aumenta la dimensión de los datos, la distancia entre los puntos se hace cada vez más similar. Esto reduce la capacidad de kNN para discriminar entre diferentes clases, ya que todos los puntos tienden a estar a una distancia similar entre sí, lo que perjudica su rendimiento.
PCA: En cambio, PCA busca proyectar los datos en un espacio de menor dimensión que captura la mayor varianza. Aunque la dimensionalidad también influye en PCA, este algoritmo puede encontrar subespacios de baja dimensión donde se conserva la mayor parte de la información, lo que lo hace menos sensible a la maldición de la dimensionalidad.

---

**2.** ¿Por qué la maldición de la dimensionalidad afecta a kNN pero es menos problemática para PCA?

**📝 Tu respuesta:** kNN: A medida que aumentan las dimensiones, las distancias entre los puntos se diluyen. En el espacio de alta dimensión, todos los puntos parecen estar más lejos unos de otros, lo que hace más difícil para el algoritmo kNN identificar vecinos cercanos. Esto afecta negativamente su rendimiento, ya que el principio de “cercanía” se vuelve menos relevante en dimensiones altas.
PCA: En cambio, PCA reduce las dimensiones a un subespacio de baja dimensión que retiene la mayor parte de la varianza en los datos. Al hacerlo, el impacto negativo de la alta dimensionalidad se mitiga, y los datos se vuelven más manejables, lo que mejora el desempeño en tareas como la visualización o el clustering.

---

**3.** ¿Por qué es útil reducir con PCA antes de aplicar K-means o DBSCAN?

**📝 Tu respuesta:** Reducir las dimensiones con PCA antes de aplicar algoritmos de clustering como K-means o DBSCAN es útil porque:

PCA elimina la redundancia: Los datos en altas dimensiones pueden tener características redundantes (correlacionadas) que no aportan valor adicional. PCA encuentra el subespacio de menor dimensión que retiene la mayor cantidad de varianza y elimina la redundancia, lo que hace que el clustering sea más eficiente.
Mejora la calidad del clustering: Los algoritmos de clustering como K-means dependen de las distancias entre puntos, y la reducción de dimensiones mejora la interpretación de las distancias al eliminar la influencia de dimensiones irrelevantes o ruidosas.

---

**4.** Observa la gráfica de contraste de distancias que se generará en el Paso 3.1.  
¿Qué ocurre con la diferencia relativa entre la distancia mínima y máxima cuando aumenta la dimensionalidad?

**📝 Tu respuesta:** A medida que aumenta la dimensionalidad, la diferencia relativa entre la distancia mínima y máxima tiende a reducirse.
Esto se debe a que en espacios de alta dimensión, las distancias entre los puntos se distribuyen de manera más uniforme, y por lo tanto, las distancias más cercanas y más lejanas tienden a acercarse. En términos simples, los puntos tienden a estar casi equidistantes unos de otros, lo que complica la tarea de identificar grupos o patrones en los datos.

---

**5.** Si K-means y DBSCAN dependen de distancias, ¿por qué la pérdida de contraste de distancias puede afectar la calidad del clustering?

**📝 Tu respuesta:** La pérdida de contraste de distancias afecta negativamente la calidad del clustering porque tanto K-means como DBSCAN utilizan distancias para agrupar los puntos.

K-means agrupa puntos que están cercanos en el espacio, pero si las distancias se vuelven similares debido a la alta dimensionalidad, el algoritmo puede no ser capaz de identificar correctamente los grupos.
DBSCAN también depende de distancias para identificar puntos como ruido o parte de un grupo. Si las distancias no se pueden distinguir claramente, DBSCAN podría fallar en la identificación de grupos y clasificar erróneamente puntos como ruido.

### 1.2 — PCA: matemática

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

Sea $\tilde{X} \in \mathbb{R}^{N \times d}$ el dataset centrado y $\Sigma = \frac{1}{N}\tilde{X}^T\tilde{X}$ la matriz de covarianza muestral.

**1.** El primer componente principal $\mathbf{v}_1$ maximiza la varianza proyectada:

$$\mathbf{v}_1 = \arg\max_{\|\mathbf{v}\|=1} \mathbf{v}^T \Sigma \mathbf{v}$$

Usando multiplicadores de Lagrange, demuestra que $\mathbf{v}_1$ debe satisfacer: $\Sigma\mathbf{v}_1 = \lambda_1 \mathbf{v}_1$.

¿Qué significa esto en términos de álgebra lineal?

**📝 Tu respuesta:** ___

---

**2.** Completa la fórmula de varianza acumulada explicada por los primeros $r$ componentes:

$$\text{VE}(r) = \frac{\sum_{k=1}^{r} \, \underline{\hspace{1.5cm}}}{\sum_{k=1}^{d} \, \underline{\hspace{1.5cm}}}$$

---

**3.** ¿Sobre qué conjunto se debe ajustar el PCA (fit) y por qué? ¿Cuál es la relación con el data leakage?

**📝 Tu respuesta:** ___

### 1.3 — K-means vs DBSCAN y pipeline

Completa el siguiente diagrama de pipeline:

```
load_breast_cancer()  →  569 muestras, 30 features
        │
        ▼
[ Paso A ] load_breast_cancer() → 569 muestras, 30 features
        │
        ▼
[ Paso B ] PCA: reducir a r* → elegir r* (¿qué criterio?)
        │
        ▼
        ├──── K-means: elegir K* elegido por el codo o silueta
        │
        └──── DBSCAN: elegir e* elegido por el gráfico de distancias o el valor de min_samples = 5
        │
        ▼
[ Paso C ] Comparación: Comparación: Evaluar calidad de los clusters generados por K-means y DBSCAN (por ejemplo, usando métricas como Silhouette Score)
```

Completa también la siguiente tabla comparativa:

| | K-means | DBSCAN |
|---|---|---|
| Forma de clusters | Forma esférica o compacta, basada en la media. | Clusters de forma arbitraria, definidos por densidad. |
| Manejo de outliers | No maneja bien los outliers, los asigna a un cluster. | Puede identificar puntos como "ruido" (outliers). |
| Parámetros clave | K (número de clusters). | Epsilon (ε) y min_samples (tamaño mínimo de puntos en un cluster). |
| Función objetivo | Minimizar la varianza intra-cluster. | Maximizar la densidad dentro de los clusters (identificar zonas densas). |

**📝 Tu respuesta:** completa los blancos arriba.

---
## Ejercicio 2 — Setup y carga de datos

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

### Paso 2.1 — Librerías
"""

UPCH_RED    = '#8B0000'
UPCH_BLUE   = '#1565C0'
UPCH_GREEN  = '#2E7D32'
UPCH_ORANGE = '#E65100'
UPCH_PURPLE = '#6A1B9A'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

# TODO 1: importa PCA desde sklearn.decomposition
from sklearn.decomposition import PCA

# TODO 2: importa KMeans y DBSCAN desde sklearn.cluster
from sklearn.cluster import KMeans, DBSCAN

from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import (silhouette_score, silhouette_samples,
                              adjusted_rand_score, davies_bouldin_score)

plt.rcParams['figure.dpi'] = 120
print('Setup completo ✓')

"""### Paso 2.2 — Carga del dataset"""

# ── Carga del dataset ──────────────────────────────────────────
data       = load_breast_cancer()
X          = data.data
feat_names = data.feature_names

print(f'Shape: {X.shape}')
print(f'Features ({len(feat_names)}): {list(feat_names[:5])} ...')
print()
print('Trabajaremos como problema NO supervisado.')
print('Las etiquetas reales se revelarán recién en el Ejercicio 6 para evaluar el clustering.')

"""### Paso 2.3 — EDA inicial: mapa de correlación"""

# ── Mapa de correlación (features originales) ──────────────────
# Este código está completo — ejecútalo y analiza el resultado

fig, ax = plt.subplots(figsize=(13, 10))
corr = pd.DataFrame(X, columns=feat_names).corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, cmap='RdBu_r', vmin=-1, vmax=1,
            annot=False, linewidths=0.3, ax=ax)
ax.set_title('Mapa de correlación — Breast Cancer Wisconsin (30 features)',
             fontsize=12, fontweight='bold', color=UPCH_RED)
plt.tight_layout()
plt.savefig('eda_correlacion.png', dpi=150, bbox_inches='tight')
plt.show()
print('→ ¿Qué observas? ¿Por qué hay tantas correlaciones altas?')

"""---
# PARTE 1 — Maldición de la Dimensionalidad y PCA
## Ejercicio 3 — Maldición de la dimensionalidad y PCA

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

### Paso 3.1 — Visualización de la maldición de la dimensionalidad
"""

# --- Maldición de la dimensionalidad ---
f = 0.01
dims = list(range(1, 51))

# Calcula la longitud de lado necesaria para capturar
# fracción f de datos en cada dimensión d
# fórmula: l(f, d) = f^(1/d)
edge_lengths = [f**(1/d) for d in dims]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(dims, edge_lengths, 'o-', color=UPCH_RED, lw=2, markersize=4)
axes[0].axvline(30, color=UPCH_BLUE, ls='--', lw=1.5,
                label=f'd=30: l={0.01**(1/30):.3f}')
axes[0].axhline(0.5, color='gray', ls=':', lw=1.2, label='l=0.5')
axes[0].set_xlabel('Dimensión d', fontsize=11)
axes[0].set_ylabel(f'Lado para capturar {100*f:.0f}% de datos', fontsize=10)
axes[0].set_title('Maldición de la dimensionalidad', fontsize=12,
                   fontweight='bold', color=UPCH_RED)
axes[0].legend(fontsize=9)
axes[0].grid(True, alpha=0.3)

# --- Cálculo del contraste de distancias kNN para cada dimensión ---
np.random.seed(42)
n_pts = 200
contrast = []
for d in range(1, 51):
    pts = np.random.uniform(0, 1, (n_pts, d))
    ref = pts[0:1, :]
    dists = np.sqrt(((pts[1:] - ref)**2).sum(axis=1))
    # Calcula c = (dists.max() - dists.min()) / dists.min()
    c = (dists.max() - dists.min()) / dists.min()
    contrast.append(c)

axes[1].plot(range(1, 51), contrast, 's-', color=UPCH_BLUE, lw=2, markersize=4)
axes[1].axvline(30, color=UPCH_RED, ls='--', lw=1.5, label='d=30')
axes[1].set_xlabel('Dimensión d', fontsize=11)
axes[1].set_ylabel('(dist_max − dist_min) / dist_min', fontsize=10)
axes[1].set_title('Pérdida de contraste kNN', fontsize=12,
                   fontweight='bold', color=UPCH_BLUE)
axes[1].legend(fontsize=9)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('curse_dimensionality.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 3.2 — PCA: varianza acumulada"""

# ── PCA: varianza acumulada ─────────────────────────────────────
# TODO 5: estandariza X con StandardScaler
scaler = StandardScaler()
X_sc   = scaler.fit_transform(X)  # Estandarizamos los datos con fit_transform

# TODO 6: crea un PCA completo (todas las componentes) y ajústalo
from sklearn.decomposition import PCA
pca_full = PCA(n_components=X_sc.shape[1])  # Crear el PCA para todas las componentes
pca_full.fit(X_sc)

var_ratio = pca_full.explained_variance_ratio_  # Proporción de varianza explicada por cada componente
var_acum  = np.cumsum(var_ratio)  # Varianza acumulada

# TODO 7: encuentra el número de componentes para ≥90% y ≥95% varianza
n_90 = np.argmax(var_acum >= 0.90) + 1  # Encuentra el número de componentes para ≥90%
n_95 = np.argmax(var_acum >= 0.95) + 1  # Encuentra el número de componentes para ≥95%
print(f'Componentes para ≥90% varianza: {n_90}')
print(f'Componentes para ≥95% varianza: {n_95}')
print(f'Varianza explicada por PC1+PC2: {var_acum[1]:.1%}')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Gráfico de varianza individual por cada componente
axes[0].bar(range(1, len(var_ratio)+1), var_ratio*100,
            color=UPCH_BLUE, alpha=0.75, edgecolor='white', linewidth=0.4)
axes[0].set_xlabel('Componente principal', fontsize=11)
axes[0].set_ylabel('Varianza explicada (%)', fontsize=11)
axes[0].set_title('Varianza individual por PC', fontsize=12,
                   fontweight='bold', color=UPCH_RED)
axes[0].set_xlim(0.5, 30.5)
axes[0].grid(True, axis='y', alpha=0.3)

# Gráfico de varianza acumulada
axes[1].plot(range(1, len(var_acum)+1), var_acum*100,
             'o-', color=UPCH_RED, lw=2, markersize=5)
axes[1].axhline(90, color=UPCH_GREEN,  ls='--', lw=1.5,
                label=f'90% → {n_90} componentes')
axes[1].axhline(95, color=UPCH_ORANGE, ls='--', lw=1.5,
                label=f'95% → {n_95} componentes')
axes[1].axvline(n_90, color=UPCH_GREEN,  ls=':', lw=1.2)
axes[1].axvline(n_95, color=UPCH_ORANGE, ls=':', lw=1.2)
axes[1].set_xlabel('Nº de componentes', fontsize=11)
axes[1].set_ylabel('Varianza acumulada (%)', fontsize=11)
axes[1].set_title('Varianza acumulada', fontsize=12,
                   fontweight='bold', color=UPCH_RED)
axes[1].legend(fontsize=9)
axes[1].grid(True, alpha=0.3)
axes[1].set_xlim(0.5, 30.5)

# Ajustes finales
plt.tight_layout()
plt.savefig('pca_varianza.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 3.3 — Proyección 2D y espacio reducido

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>
"""

# ── PCA: proyección 2D y espacio reducido ──────────────────────
# TODO 8: crea PCA con 2 componentes y proyecta X_sc → Z_2d
pca_2d = PCA(n_components=2)  # Crea PCA con 2 componentes
Z_2d   = pca_2d.fit_transform(X_sc)  # Proyecta X_sc en el nuevo espacio de 2D

# TODO 9: crea PCA con n_90 componentes y proyecta X_sc → Z_pca
#          (este es el espacio que usaremos para clustering)
pca_r = PCA(n_components=n_90)  # Crea PCA con n_90 componentes
Z_pca = pca_r.fit_transform(X_sc)  # Proyecta X_sc en el nuevo espacio reducido
print(f'Espacio reducido para clustering: {Z_pca.shape}')  # Imprime la forma del nuevo espacio reducido

# Gráfica 2D de la proyección PCA
fig, ax = plt.subplots(figsize=(8, 6))
ax.scatter(Z_2d[:, 0], Z_2d[:, 1],
           alpha=0.5, s=15, color=UPCH_BLUE, edgecolors='none')
ax.set_xlabel(f'PC1  ({var_ratio[0]:.1%} varianza)', fontsize=11)
ax.set_ylabel(f'PC2  ({var_ratio[1]:.1%} varianza)', fontsize=11)
ax.set_title('Proyección PCA 2D — Breast Cancer Wisconsin\n(sin etiquetas)',
             fontsize=12, fontweight='bold', color=UPCH_RED)
ax.grid(True, alpha=0.2)
plt.tight_layout()
plt.savefig('pca_2d_sin_etiquetas.png', dpi=150, bbox_inches='tight')
plt.show()

print('→ ¿Intuyes alguna estructura de grupos en la proyección 2D?')

"""### Paso 3.4 — Interpretación

**📝 Tu respuesta (edita esta celda):**

**1. ¿Qué porcentaje de varianza captura PC1? ¿Qué tipo de información podría estar codificando en este dataset clínico?**
PC1 captura 44.3% de la varianza total del dataset.
El tipo de información que PC1 podría estar codificando podría ser alguna propiedad general de las características de los tumores, como el tamaño o la textura general, que refleja una alta variabilidad entre los diferentes ejemplos.

**2. ¿Por qué se aplica StandardScaler ANTES de PCA?**
Se aplica StandardScaler para que las diferentes características del dataset tengan la misma escala. PCA es sensible a las escalas de las variables, y si no se realiza la estandarización, las variables con mayor rango o unidades dominarían la proyección de PCA. La normalización garantiza que cada característica tenga la misma importancia.

**3. ¿Sobre qué conjunto se debe hacer fit() del PCA si se dividiera en train/test? ¿Por qué?**
Se debe hacer fit() sobre el conjunto de entrenamiento (train) y no sobre el conjunto de prueba (test). Esto es porque el objetivo es entrenar el modelo de PCA en los datos de entrenamiento y luego transformarlo sobre los datos de prueba. Realizar PCA sobre todo el dataset antes de la división introduciría información de los datos de test, lo que podría llevar a overfitting y generar resultados sesgados.

**4. ¿Cuánta varianza explican PC1 + PC2? ¿Crees que 2 componentes son suficientes para análisis cuantitativo o solo para visualización?**
PC1 y PC2 explican juntas aproximadamente 63.2% de la varianza total del dataset.
Dos componentes podrían ser suficientes para visualización, ya que explican la mayor parte de la varianza, pero para un análisis cuantitativo más preciso es posible que se necesiten más componentes, dependiendo de cuánta información se desea conservar.

**5. ¿Cuántas componentes se necesitan para explicar al menos 90% y 95% de la varianza? ¿Qué decisión tomarías para clustering?**
Para explicar el 90% de la varianza se necesitan 7 componentes y para el 95% se necesitan 10 componentes.
Para clustering, una decisión conservadora sería elegir 7 componentes, ya que alcanzan el 90% de la varianza y aún se conserva una gran parte de la información original. Sin embargo, si se requiere mayor precisión en la captura de variabilidad, se podría optar por usar 10 componentes.

---
# PARTE 2 — K-means Clustering
## Ejercicio 4 — K-means: selección de K y análisis

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>

### Paso 4.1 — Método del codo y Silhouette score
"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score

# ── Método del codo (Elbow) + Silhouette ───────────────────────
K_range = range(2, 11)
inertias = []
sil_scores = []
db_scores = []

for k in K_range:
    # TODO 10: crea KMeans con n_clusters=k, random_state=42, n_init=10
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(Z_pca)

    # TODO 11: agrega inercia y silhouette score a las listas
    inertias.append(km.inertia_)  # Inertia (WCSS)
    sil_scores.append(silhouette_score(Z_pca, labels))  # Silhouette score
    db_scores.append(davies_bouldin_score(Z_pca, labels))  # Davies-Bouldin score
    print(f'K={k}  inertia={inertias[-1]:>10.1f}  silhouette={sil_scores[-1]:.4f}')

# Visualización de los resultados
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Método del Codo
axes[0].plot(list(K_range), inertias, 'o-', color=UPCH_RED, lw=2, markersize=7)
axes[0].set_xlabel('K', fontsize=11)
axes[0].set_ylabel('Inercia (WCSS)', fontsize=11)
axes[0].set_title('Método del Codo', fontsize=12, fontweight='bold', color=UPCH_RED)
axes[0].grid(True, alpha=0.3)

# Silhouette Score vs K
axes[1].plot(list(K_range), sil_scores, 's-', color=UPCH_BLUE, lw=2, markersize=7)
axes[1].set_xlabel('K', fontsize=11)
axes[1].set_ylabel('Silhouette score', fontsize=11)
axes[1].set_title('Silhouette Score vs K', fontsize=12, fontweight='bold', color=UPCH_BLUE)
axes[1].grid(True, alpha=0.3)

# Davies-Bouldin Score vs K (Menor es mejor)
axes[2].plot(list(K_range), db_scores, '^-', color=UPCH_GREEN, lw=2, markersize=7)
axes[2].set_xlabel('K', fontsize=11)
axes[2].set_ylabel('Davies-Bouldin score', fontsize=11)
axes[2].set_title('Davies-Bouldin Score vs K\n(menor = mejor)', fontsize=12, fontweight='bold', color=UPCH_GREEN)
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('kmeans_seleccion_k.png', dpi=150, bbox_inches='tight')
plt.show()

# TODO 12: elige el K óptimo según silhouette score máximo
best_k = K_range[sil_scores.index(max(sil_scores))]  # K óptimo para el máximo silhouette score
print(f'K óptimo: {best_k}  (silhouette={max(sil_scores):.4f})')

"""### Paso 4.2 — Diagrama de Silhouette para K óptimo"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm

# ── Diagrama de Silhouette para K óptimo ───────────────────────
# TODO 13: entrena KMeans final con best_k
km_best = KMeans(n_clusters=best_k, random_state=42, n_init=10)
labels_km = km_best.fit_predict(Z_pca)

sil_vals = silhouette_samples(Z_pca, labels_km)
sil_avg  = sil_vals.mean()

# Plot de Silhouette
fig, ax = plt.subplots(figsize=(9, 5))
y_lower = 10
colors_sil = cm.Set1(np.linspace(0, 0.9, best_k))

for k in range(best_k):
    sil_k = np.sort(sil_vals[labels_km == k])
    size_k = sil_k.shape[0]
    y_upper = y_lower + size_k
    ax.fill_betweenx(np.arange(y_lower, y_upper), 0, sil_k,
                     alpha=0.75, color=colors_sil[k],
                     label=f'Cluster {k} (n={size_k})')
    y_lower = y_upper + 10

ax.axvline(sil_avg, color='red', ls='--', lw=1.5,
           label=f'Media = {sil_avg:.3f}')
ax.set_xlabel('Silhouette coefficient', fontsize=11)
ax.set_title(f'Diagrama de Silhouette — K-means (K={best_k})',
             fontsize=12, fontweight='bold', color=UPCH_RED)
ax.legend(fontsize=9)
ax.set_yticks([])
ax.grid(True, axis='x', alpha=0.3)

plt.tight_layout()
plt.savefig('silhouette_kmeans.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 4.3 — Visualización de clusters en espacio PCA"""

# ── K-means: visualización en espacio PCA 2D ───────────────────
# km_best fue entrenado directamente sobre Z_pca (PC1...PC_r).
# Por tanto, sus centroides YA están en espacio PCA reducido.
# Para graficarlos en PC1 vs PC2 basta tomar sus dos primeras coordenadas.
# Se usa Z_2d (= las mismas PC1 y PC2) para que todos los plots del challenge
# compartan la misma variable de visualización y no haya inconsistencias.
centroids_2d = km_best.cluster_centers_[:, :2]

fig, ax = plt.subplots(figsize=(9, 7))
colors_km = [UPCH_RED, UPCH_BLUE, UPCH_GREEN, UPCH_ORANGE, UPCH_PURPLE]

for k in range(best_k):
    mask = labels_km == k
    ax.scatter(Z_2d[mask, 0], Z_2d[mask, 1],
               alpha=0.5, s=20, color=colors_km[k % len(colors_km)],
               label=f'Cluster {k} (n={mask.sum()})', edgecolors='none')

ax.scatter(centroids_2d[:, 0], centroids_2d[:, 1],
           c='black', marker='*', s=300, zorder=5, label='Centroides')

ax.set_xlabel(f'PC1  ({var_ratio[0]:.1%})', fontsize=11)
ax.set_ylabel(f'PC2  ({var_ratio[1]:.1%})', fontsize=11)
ax.set_title(f'K-means (K={best_k}) en espacio PCA 2D',
             fontsize=12, fontweight='bold', color=UPCH_RED)
ax.legend(fontsize=9)
ax.grid(True, alpha=0.2)
plt.tight_layout()
plt.savefig('kmeans_clusters_pca.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 4.4 — Interpretación

**📝 Tu respuesta (edita esta celda):**

**1. ¿El método del codo da un K claro? ¿Hay coherencia entre el codo y el peak de silhouette?**
El método del codo muestra una clara caída en la inercia con el aumento de K, que se estabiliza en un valor más bajo a partir de cierto K (en este caso, K=2 parece ser el valor óptimo). Sin embargo, el silhouette score comienza a disminuir después de un cierto punto (K=2), lo que sugiere que K=2 podría ser la mejor opción para optimizar la separación de los clusters.

**2. ¿Qué implica un silhouette score negativo para alguna muestra?**
Un silhouette score negativo indica que la muestra probablemente está mal agrupada, es decir, que la muestra se encuentra más cerca de los puntos de otro cluster que de su propio cluster.

**3. ¿Por qué se visualiza en el espacio PCA 2D si el clustering se hizo en el espacio PCA de n_90 componentes?**
El espacio PCA 2D se usa para visualizar el clustering en una representación comprensible, ya que el espacio reducido de 2 dimensiones (PC1 y PC2) facilita la interpretación visual. Sin embargo, el clustering real se hace en el espacio de 90 componentes, lo cual permite preservar una mayor cantidad de varianza.

**4. Si eliges un K demasiado pequeño, ¿qué problema aparece? ¿Y si eliges un K demasiado grande?**
Si el valor de K es demasiado pequeño, se corre el riesgo de subdividir grupos significativos en clusters que no reflejan correctamente la estructura de los datos. Si el valor de K es demasiado grande, podría sobregeneralizar los clusters, resultando en grupos que contienen muestras que no son similares entre sí, lo que puede reducir la calidad del clustering.

**5. En un problema biomédico real, ¿usarías solo el método del codo para elegir K? Justifica tu respuesta.**
No, el método del codo solo debe ser usado como una referencia inicial. Para un problema biomédico real, también se debe considerar el silhouette score y otras métricas, como el Davies-Bouldin score, para garantizar que los clusters sean consistentes y representen correctamente las categorías o patrones en los datos.

---
# PARTE 3 — DBSCAN
## Ejercicio 5 — DBSCAN: selección de parámetros y análisis

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>

### Paso 5.1 — k-distance graph para selección de ε
"""

# ── k-distance graph para selección de ε ────────────────────────
# Heurística: Ester et al. recomiendan ≥ d+1; se usa max(5, n_90+1)
# para evitar que DBSCAN sea excesivamente restrictivo con d pequeño.
MIN_SAMPLES = max(5, n_90 + 1)
print(f'min_samples = {MIN_SAMPLES}  (heurística: max(5, d+1) con d={n_90})')

nbrs   = NearestNeighbors(n_neighbors=MIN_SAMPLES).fit(Z_pca)
dists, _ = nbrs.kneighbors(Z_pca)

# TODO 14: extrae la distancia al k-ésimo vecino de cada punto
#           y ordénala de mayor a menor
k_dists = np.sort(dists[:, -1], axis=0)  # Ordenamos la distancia al k-ésimo vecino
# 'dists[:, -1]' selecciona la última columna, que corresponde al k-ésimo vecino

fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(k_dists, color=UPCH_RED, lw=1.5)
ax.set_xlabel('Muestras (ordenadas por distancia al k-vecino desc.)', fontsize=11)
ax.set_ylabel(f'{MIN_SAMPLES}-NN distance', fontsize=11)
ax.set_title(f'k-distance graph (k={MIN_SAMPLES}) — selección de ε',
             fontsize=12, fontweight='bold', color=UPCH_RED)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('dbscan_kdist.png', dpi=150, bbox_inches='tight')
plt.show()
print('→ Identifica el codo de la curva — ese valor es tu ε óptimo.')

"""### Paso 5.2 — DBSCAN"""

# ── DBSCAN ──────────────────────────────────────────────────────
# Detecta el codo del k-distance graph (punto de máxima curvatura).
# El percentil-10 no siempre corresponde al codo visual — este método
# es más robusto. Revisa la gráfica del Paso 5.1 y ajusta si es necesario.
from numpy.linalg import norm as _norm

def _find_elbow(y):
    x = np.arange(len(y), dtype=float)
    p1, p2 = np.array([x[0], y[0]]), np.array([x[-1], y[-1]])
    d = p2 - p1; d = d / _norm(d)
    perp = np.array([abs(np.cross(d, np.array([x[i], y[i]]) - p1))
                     for i in range(len(y))])
    return int(np.argmax(perp))

# TODO 15a: el codo ya se detecta automáticamente abajo;
#            revisa la gráfica anterior y ajusta EPS si no coincide visualmente
elbow_idx = _find_elbow(k_dists)
EPS = float(k_dists[elbow_idx])
print(f'ε detectado: {EPS:.4f}  (ajusta si no coincide con el codo visual)')

# TODO 15: crea y ajusta DBSCAN con eps=EPS, min_samples=MIN_SAMPLES
db = DBSCAN(eps=EPS, min_samples=MIN_SAMPLES)
labels_db = db.fit_predict(Z_pca)

n_clusters_db = len(set(labels_db)) - (1 if -1 in labels_db else 0)
n_noise = (labels_db == -1).sum()
print(f'Clusters encontrados: {n_clusters_db}')
print(f'Puntos de ruido: {n_noise} ({100*n_noise/len(labels_db):.1f}%)')

if n_clusters_db > 1:
    mask_valid = labels_db != -1
    sil_db = silhouette_score(Z_pca[mask_valid], labels_db[mask_valid])
    print(f'Silhouette (sin ruido): {sil_db:.4f}')

"""### Paso 5.2.1 — Sensibilidad de DBSCAN a `eps`

DBSCAN puede cambiar mucho cuando se modifica `eps`. Prueba valores menores y mayores que el elegido inicialmente para observar el efecto sobre:

- número de clusters,
- número de puntos de ruido,
- silhouette score cuando sea posible.


"""

# ── Sensibilidad de DBSCAN a eps ────────────────────────────────
# TODO 16: prueba al menos 3 valores de eps alrededor del valor inicial
# Sugerencia: usa 0.7*EPS, EPS y 1.3*EPS
eps_values = [0.7 * EPS, EPS, 1.3 * EPS]

rows = []
for eps in eps_values:
    db_tmp = DBSCAN(eps=eps, min_samples=MIN_SAMPLES)
    labels_tmp = db_tmp.fit_predict(Z_pca)

    n_clusters_tmp = len(set(labels_tmp)) - (1 if -1 in labels_tmp else 0)
    n_noise_tmp = int((labels_tmp == -1).sum())

    if n_clusters_tmp > 1:
        mask_valid = labels_tmp != -1
        sil_tmp = silhouette_score(Z_pca[mask_valid], labels_tmp[mask_valid])
    else:
        sil_tmp = np.nan

    rows.append({
        'eps': eps,
        'n_clusters': n_clusters_tmp,
        'n_noise': n_noise_tmp,
        'noise_%': 100*n_noise_tmp/len(labels_tmp),
        'silhouette_sin_ruido': sil_tmp
    })

df_eps = pd.DataFrame(rows)
df_eps

"""### Paso 5.3 — Visualización en espacio PCA"""

# ── DBSCAN: visualización en espacio PCA 2D ────────────────────
fig, ax = plt.subplots(figsize=(9, 7))

# Get the unique labels for the clusters, including noise (-1)
unique_labels = sorted(set(labels_db))

# Define colors for each cluster
colors_db  = cm.tab10(np.linspace(0, 0.9, max(n_clusters_db, 1)))
color_idx  = 0

# Loop through each label to plot clusters and noise points
for label in unique_labels:
    mask = labels_db == label
    if label == -1:  # For noise points
        ax.scatter(Z_2d[mask, 0], Z_2d[mask, 1],
                   alpha=0.3, s=12, color='gray',
                   marker='x', label=f'Ruido (n={mask.sum()})')
    else:  # For clusters
        ax.scatter(Z_2d[mask, 0], Z_2d[mask, 1],
                   alpha=0.6, s=20, color=colors_db[color_idx],
                   edgecolors='none', label=f'Cluster {label} (n={mask.sum()})')
        color_idx += 1

# Set labels and title
ax.set_xlabel(f'PC1  ({var_ratio[0]:.1%})', fontsize=11)
ax.set_ylabel(f'PC2  ({var_ratio[1]:.1%})', fontsize=11)
ax.set_title(f'DBSCAN (ε={EPS:.3f}, min_samples={MIN_SAMPLES})',
             fontsize=12, fontweight='bold', color=UPCH_RED)

# Display legend and grid
ax.legend(fontsize=9)
ax.grid(True, alpha=0.2)

# Tight layout and saving the figure
plt.tight_layout()
plt.savefig('dbscan_clusters_pca.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 5.4 — Interpretación

**📝 Tu respuesta (edita esta celda):**

**1. ¿Cuántos clusters encontró DBSCAN? ¿Coincide con la estructura visual del PCA 2D?**
DBSCAN detectó 2 clusters en este caso. En la visualización 2D de PCA, estos clusters se muestran claramente separados en dos grupos distintos. Los puntos de ruido, que son más dispersos, no forman parte de los clusters y se muestran en gris.

**2. ¿Qué representan clínicamente los puntos de ruido en este dataset?**
Los puntos de ruido en este dataset representan datos atípicos o ejemplos que no encajan bien en ninguno de los clusters definidos. En un contexto biomédico, estos podrían ser registros de pacientes con características inusuales o anomalías que no corresponden a las categorías de cáncer maligno o benigno, y que por tanto, DBSCAN no los agrupa correctamente.

**3. ¿Cómo afecta cambiar ε al número de clusters y de puntos de ruido? Prueba al menos 2 valores distintos.**
Cambiar el valor de ε afecta directamente al número de clusters detectados por DBSCAN:

Si ε es pequeño, el algoritmo puede detectar más puntos como ruido, lo que reduce el número de clusters.
Si ε es grande, el algoritmo puede agrupar más puntos, lo que aumenta el número de clusters.

Por ejemplo:

Para un ε pequeño, DBSCAN podría no encontrar muchos clusters, pero podría generar más puntos de ruido.
Para un ε grande, DBSCAN podría agrupar puntos que anteriormente estaban fuera de los clusters, resultando en menos puntos de ruido pero más clusters generados.

**4. A partir de la tabla de sensibilidad, ¿qué ocurre si `eps` es muy pequeño? ¿Y si `eps` es muy grande?**
Si ε es muy pequeño, es probable que el modelo detecte una gran cantidad de puntos de ruido, y puede que no forme clusters adecuados. Esto ocurriría porque los puntos no pueden agruparse por estar demasiado lejos entre sí.
Si ε es muy grande, DBSCAN puede agrupar muchos puntos que no deberían pertenecer al mismo grupo, reduciendo el número de clusters y aumentando el riesgo de sobreajuste. Esto podría generar un modelo que no refleja correctamente las verdaderas separaciones entre los datos.

---
# PARTE 4 — Comparación Final
## Ejercicio 6 — Evaluación contra etiquetas reales

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>

### Paso 6.1 — Adjusted Rand Index y métricas comparativas
"""

# ── Comparación con etiquetas reales ───────────────────────────
# ⚠️  PRIMERA VEZ que usamos y_true — revelamos las etiquetas reales solo al final
y_true = data.target

print(f'Clases reales: {data.target_names}  →  0=maligno, 1=benigno')
print(f'Distribución real: maligno={(y_true==0).sum()}, benigno={(y_true==1).sum()}')
print()

from scipy.optimize import linear_sum_assignment
from sklearn.metrics import confusion_matrix as cm_func

def best_label_mapping(y_true, y_pred):
    cm = cm_func(y_true, y_pred)
    row_ind, col_ind = linear_sum_assignment(-cm)
    mapping = {col: row for col, row in zip(col_ind, row_ind)}
    return np.array([mapping.get(l, l) for l in y_pred])

labels_km_mapped = best_label_mapping(y_true, labels_km)

# TODO 16: calcula el ARI de K-means contra y_true
from sklearn.metrics import adjusted_rand_score as ari_func
ari_km = ari_func(y_true, labels_km_mapped)  # Ajusta las etiquetas de K-means según el mapeo

# TODO 17a: calcula el ARI crudo de DBSCAN contra y_true
ari_db_raw = ari_func(y_true, labels_db)

# TODO 17b: si DBSCAN tiene solo 1 cluster útil, reporta 0.0 como ARI clínico.
# Si tiene más de 1 cluster útil, usa ari_db_raw.
ari_db = ari_db_raw if n_clusters_db > 1 else 0.0

# TODO 18: calcula silhouette de K-means y de DBSCAN (sin ruido)
from sklearn.metrics import silhouette_score
sil_km = silhouette_score(Z_pca[labels_km != -1], labels_km[labels_km != -1])  # Silhouette sin ruido en K-means
sil_db = silhouette_score(Z_pca[labels_db != -1], labels_db[labels_db != -1]) if n_clusters_db > 1 else 0.0  # DBSCAN sin ruido

# TODO 19: calcula Davies-Bouldin de K-means y DBSCAN (sin ruido)
from sklearn.metrics import davies_bouldin_score
db_km = davies_bouldin_score(Z_pca[labels_km != -1], labels_km[labels_km != -1])  # Davies-Bouldin para K-means
db_db = davies_bouldin_score(Z_pca[labels_db != -1], labels_db[labels_db != -1]) if n_clusters_db > 1 else float('nan')  # DBSCAN sin ruido

print('=' * 86)
print('    COMPARACIÓN FINAL — K-means vs DBSCAN vs Etiquetas Reales')
print('=' * 86)
print(f'{"Método":<20} {"ARI clínico":^12} {"ARI crudo":^11} {"Silhouette":^12} {"Davies-Bouldin":^16} {"Clusters"}')
print('-' * 86)
print(f'{"K-means":<20} {ari_km:^12.4f} {ari_km:^11.4f} {sil_km:^12.4f} {db_km:^16.4f} {best_k}')
print(f'{"DBSCAN":<20} {ari_db:^12.4f} {ari_db_raw:^11.4f} {sil_db:^12.4f} {db_db:^16.4f} {n_clusters_db} (+{n_noise} ruido)')
print()
print('Interpretación: ARI→1=perfecto | Silhouette→+1=mejor | Davies-Bouldin→0=mejor')
if n_clusters_db <= 1:
    print('Nota DBSCAN: aunque el ARI crudo puede calcularse usando ruido=-1, se reporta ARI clínico=0.0 porque solo hay 1 cluster útil.')

"""### Paso 6.2 — Visualización comparativa"""

# ── Visualización comparativa: K-means vs DBSCAN vs Ground Truth
fig, axes = plt.subplots(1, 3, figsize=(18, 6))
gt_labels = ['Maligno', 'Benigno']

configs = [
    (labels_km_mapped, [UPCH_BLUE, UPCH_RED],
     f'K-means (K={best_k})\nARI={ari_km:.3f}', False),
    (labels_db, None,
     f'DBSCAN (ε={EPS:.3f})\nARI={ari_db:.3f}', False),
    (y_true, [UPCH_BLUE, UPCH_RED],
     'Ground Truth\n(revelado al final)', True),
]

for ax, (labels, cols, title, is_gt) in zip(axes, configs):
    unique = sorted(set(labels))

    # Usar una paleta adecuada para los colores
    if cols is None:
        palette = ['gray'] + list(cm.tab10(np.linspace(0, 0.7, max(len(unique)-1, 1))))  # Corregido aquí
    else:
        palette = cols + ['gray']

    for i, lbl in enumerate(unique):
        mask = labels == lbl
        lbl_name = ('Ruido' if lbl == -1 else
                    (gt_labels[lbl] if is_gt else f'Cluster {lbl}'))

        # Asignación correcta de color con `c=palette[i % len(palette)]`
        ax.scatter(Z_2d[mask, 0], Z_2d[mask, 1],
                   alpha=0.5, s=14, c=palette[i % len(palette)],  # Se usa `c=` para asignar el color
                   edgecolors='none', label=f'{lbl_name} ({mask.sum()})')

    ax.set_title(title, fontsize=11, fontweight='bold', color=UPCH_RED)
    ax.set_xlabel(f'PC1 ({var_ratio[0]:.1%})', fontsize=9)
    ax.set_ylabel(f'PC2 ({var_ratio[1]:.1%})', fontsize=9)
    ax.legend(fontsize=8, markerscale=1.5)
    ax.grid(True, alpha=0.2)

plt.suptitle('Comparación Final — Clustering vs Diagnóstico Real',
             fontsize=13, fontweight='bold', color=UPCH_RED, y=1.02)

plt.tight_layout()
plt.savefig('comparacion_final.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 6.3 — Interpretación final

**📝 Tu respuesta (edita esta celda):**

**1. ¿Qué ARI obtuvo K-means? ¿Qué significa ese valor clínicamente?**
K-means obtuvo un ARI = 0.6707. Clínicamente, esto indica una correspondencia moderada-alta entre los clusters encontrados sin etiquetas y el diagnóstico real maligno/benigno. No es perfecto, pero sí muestra que las 30 variables morfológicas contienen información relevante para separar ambos grupos.

**2. ¿K-means o DBSCAN recuperó mejor la distinción maligno/benigno? ¿Por qué?**
K-means recuperó mejor la distinción maligno/benigno, porque obtuvo un ARI mucho mayor (0.6707) y formó 2 clusters, coherentes con las dos clases clínicas. DBSCAN encontró solo 1 cluster útil y varios puntos de ruido, por lo que no logró separar adecuadamente malignos y benignos.

**3. Tabla resumen — completa con los valores obtenidos:**

| Método | ARI clínico | ARI crudo | Silhouette | Davies-Bouldin | Nº clusters | Ruido |
|---|---:|---:|---:|---:|---:|---:|
| K-means | 0.6707 | 0.6707 | 0.3710 | 1.2159 | 2 | 0 |
| DBSCAN | 0 | 0.0335| 0| NaN | 1 | 30 |

**4. ¿Qué nos dice el ARI sobre el valor clínico de las 30 features morfológicas del FNA?**
El ARI muestra que las variables morfológicas del FNA tienen valor clínico, porque permiten recuperar parcialmente la separación entre tumores malignos y benignos sin usar etiquetas durante el entrenamiento.

**5. ¿En qué escenario clínico sería útil el aprendizaje no supervisado si no se tuviera el diagnóstico histológico disponible?**
Sería útil en análisis exploratorio de biopsias cuando aún no se cuenta con diagnóstico histológico, para detectar subgrupos de pacientes, identificar casos atípicos y priorizar muestras que requieran mayor revisión médica.
"""